version: '1.0'

services: 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    networks:
      - app_network

  server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}
    networks:
      - app_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  ml_model:
    build:
      context: ./ml
      dockerfile: Dockerfile.ml
    container_name: ml_model
    depends_on:
      - mongodb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
    name: mongodb_data
